/*
 * (C) Copyright 2025 Synaptics Incorporated. All rights reserved.
 *
 * This program is the proprietary software of Synaptics and/or its licensors,
 * and may only be used, duplicated, modified or distributed under the authorized
 * license from Synaptics.
 * ANY USE OF THE SOFTWARE OTHER THAN AS AUTHORIZED UNDER THIS LICENSE OR
 * COPYRIGHT LAW IS PROHIBITED.
 */

/*********************    Autogenerated file. DO NOT EDIT *******************
 * Generated from class.tflite file.
 * Date: 2025-04-12 18:49:48.052526
 ***************************************************************************/

#include <cstddef>
#include <cstdint> 
#include "inference_attributes.hpp"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
 
namespace model_class_flash {
    constexpr int kNumberOperators = 2;
    tflite::MicroMutableOpResolver<kNumberOperators> micro_op_resolver;
    static bool initialized = false;
    tflite::MicroOpResolver& get_resolver(void) {
	if (initialized == false) { 
	    micro_op_resolver.AddEthosU();
	    micro_op_resolver.AddFullyConnected();
	    initialized = true;
	}
	return micro_op_resolver;
    }
} /* namespace model_flash */

